name: Test and publish
on:
  push:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  test:
    name: Test and publish the thesis
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:2.11.0-9-g19f2f60
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Typeset the thesis
        run: latexmk main

      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            main.pdf

      - name: Create a release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The typeset doctoral thesis
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            main.pdf
