name: Test
on:
  push:
    branches: ['**', '!main']
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  test:
    name: Test the doctoral thesis and the thesis defense presentation
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:TL2020-historic
    steps:
      - name: Check that there are no repeating footnote labels in the thesis
        run: |
          sed -n '/^ *\[\^/s/:.*//p' main.md | sort | uniq -dD | { ! grep .; }

      - name: Install GraphViz
        run: |
          set -e
          apt-get -qy update
          apt-get -qy install --no-install-recommends graphviz

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Typeset the doctoral thesis
        run: |
          latexmk thesis

      - name: Typeset the thesis defense presentation slides
        run: |
          latexmk -Werror presentation

      - name: Typeset the thesis defense presentation notes
        run: |
          latexmk -Werror notes

      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            thesis.pdf
            presentation.pdf
            notes.pdf
