name: Test and publish
on:
  push:
    branches: ['main']
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TEXMFVAR: /var/tmp/texmf-var
jobs:
  test:
    name: Test and publish the doctoral thesis and the thesis defense presentation
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:latest-with-cache
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Check that there are no repeating footnote and link labels in the thesis
        shell: bash {0}
        run: |
          set -e -o pipefail
          sed -n '/^ *\[/s/:.*//p' main.md | sort | uniq -dD | { ! grep .; }

      - name: Check that there are no repeating footnote and link labels in the thesis defense
        shell: bash {0}
        run: |
          set -e -o pipefail
          sed -n '/^ *\[/s/:.*//p' defense.md | sort | uniq -dD | { ! grep .; }

      - name: Install GraphViz and pdf2txt
        run: |
          set -e
          apt-get -qy update
          apt-get -qy install --no-install-recommends graphviz python3-pdfminer

      - name: Install pdfannotextractor
        run: |
          set -e
          mkdir -v -p /var/tmp/texmf-var
          pdfannotextractor --install

      - name: Extract annotations from publications
        shell: bash {0}
        run: |
          set -e
          shopt -s extglob
          pdfannotextractor publications/!(novotny2018implementation|sojka2018mias).pdf

      - name: Typeset the doctoral thesis
        run: |
          latexmk thesis

      - name: Check the number of pages in the doctoral thesis
        shell: bash {0}
        run: |
          set -e -o pipefail
          [ $(pdfinfo thesis.pdf | grep -a  'Pages:' | awk '{print $2}') = 316 ]

      - name: Typeset the thesis defense presentation slides
        run: |
          latexmk presentation

      - name: Check the number of pages in the presentation slides
        shell: bash {0}
        run: |
          set -e -o pipefail
          [ $(pdfinfo presentation.pdf | grep -a  'Pages:' | awk '{print $2}') = 71 ]

      - name: Typeset the thesis defense presentation notes
        run: |
          latexmk -Werror notes

      - name: Estimate the length of the thesis defense presentation notes
        run: |
          set -e
          printf 'Summary length: %d minutes\n'  $(($(pdf2txt notes.pdf | sed -n '/^Summary$/,/^Rebuttal$/p' | wc -w) / 140))
          printf 'Rebuttal length: %d minutes\n' $(($(pdf2txt notes.pdf | sed -n '/^Rebuttal$/,/^References$/p' | wc -w) / 140))

      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            thesis.pdf
            presentation.pdf
            notes.pdf

      - name: Create a release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The typeset doctoral thesis and thesis defense presentation
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            thesis.pdf
            presentation.pdf
            notes.pdf
