name: Test
on:
  push:
    branches: ['**', '!main']
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  test:
    name: Test the thesis
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:2.13.0-3-g388b1a8-latest-with-cache
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Typeset the thesis
        run: latexmk main
